<script type="text/javascript">
    $(function(){
    });
</script>

<form id="position-report" method="post">  
    <p>位置汇报</p>
    <div>  
        <label for="name">Name:</label>  
        <input class="easyui-validatebox" type="text" name="name" data-options="required:true" />  
    </div>  
    <div>  
        <label for="email">Email:</label>  
        <input class="easyui-validatebox" type="text" name="email" data-options="validType:'email'" />  
    </div>  
</form>  