<script type="text/javascript">
    function cmd(cmdhref) {
        $('#send-cmd-layout').layout('remove', 'center');
        $('#send-cmd-layout').layout('add', {
            region: 'center',
            fit: true,
            href: GetBaseUrl() + "/monitor/index/" + cmdhref
        });
    }
</script>

<div id="send-cmd-layout" class="easyui-layout" data-options="fit:true">
    <div data-options="region:'west',split:true" style="width:200px" >
        <ul>
            <li><a href='#' class="easyui-linkbutton" data-options="plain:true" onclick="cmd('setterminal');">设置终端参数</a></li>
            <li><a href='#' class="easyui-linkbutton" data-options="plain:true" onclick="cmd('terminalcontrol');">终端控制</a></li>
            <li><a href='#' class="easyui-linkbutton" data-options="plain:true">临时位置跟踪控制</a></li>
            <li><a href='#' class="easyui-linkbutton" data-options="plain:true">文本信息下发</a></li>
            <li><a href='#' class="easyui-linkbutton" data-options="plain:true">提问下发</a></li>
            <li><a href='#' class="easyui-linkbutton" data-options="plain:true">电话回拨</a></li>
            <li><a href='#' class="easyui-linkbutton" data-options="plain:true">设置电话本</a></li>
            <li><a href='#' class="easyui-linkbutton" data-options="plain:true">车辆控制</a></li>
            <li><a href='#' class="easyui-linkbutton" data-options="plain:true">上报驾驶员身份信息请求</a></li>
            <li><a href='#' class="easyui-linkbutton" data-options="plain:true">摄像头立即拍摄命令</a></li>
            <li><a href='#' class="easyui-linkbutton" data-options="plain:true">录音开始命令</a></li>
        </ul>
    </div>  
    <div data-options="region:'center',fit:true" >
    </div>  
</div>  