<script type="text/javascript">
    $(function() {
        $('#tabs-terminal-parameter').tabs({
            border: true
        });
    });
</script>
<div id="tabs-terminal-parameter" class="easyui-tabs" data-options="fit:true">  
    <div title="网络参数" data-options="closable:false,href:'/monitor/index/setnetwork'" style="padding:20px;">  
    </div>  
    <div title="位置汇报参数" data-options="closable:false,href:'/monitor/index/positionreport'" style="padding:20px;">  
    </div>  
    <div title="电话通讯参数" data-options="closable:false" style="padding:20px;">  
    </div>
    <div title="报警参数" data-options="closable:false" style="padding:20px;">  
    </div>  
    <div title="多媒体参数" data-options="closable:false" style="padding:20px;">  
    </div>  
    <div title="GNSS参数" data-options="closable:false" style="padding:20px;">  
    </div>  
</div>  