<?php echo '<table idd="mask_bit" id="' . $this->escape($this->mask_id) . '">' ?>
    <tr>
        <td>
            <input type="checkbox" name="0" value ="0" >紧急报警</input>
        </td>
        <td>
            <input type="checkbox" name="1" value ="0" >超速报警</input>
        </td>
        <td>
            <input type="checkbox" name="2" value ="0" >疲劳驾驶</input>
        </td>
        <td>
            <input type="checkbox" name="3" value ="0" >危险预警</input>
        </td>
        <td>
            <input type="checkbox" name="4" value ="0" >GNSS模块发生故障</input>
        </td>
    </tr>
    <tr>
        <td>
            <input type="checkbox" name="5" value ="0" >GNSS天线未接或被剪断</input>
        </td>
        <td>
            <input type="checkbox" name="6" value ="0" >GNSS天线短路</input>
        </td>
        <td>
            <input type="checkbox" name="7" value ="0" >终端主电源欠压</input>
        </td>
        <td>
            <input type="checkbox" name="8" value ="0" >终端主电源掉电</input>
        </td>
        <td>
            <input type="checkbox" name="9" value ="0" >终端LCD或显示器故障</input>
        </td>
    </tr>
    <tr>
        <td>
            <input type="checkbox" name="10" value ="0" >TTS模块故障</input>
        </td>
        <td>
            <input type="checkbox" name="11" value ="0" >摄像头故障</input>
        </td>
        <td>
            <input type="checkbox" name="12" value ="0" >道路运输证IC卡模块故障</input>
        </td>
        <td>
            <input type="checkbox" name="13" value ="0" >超速预警</input>
        </td>
        <td>
            <input type="checkbox" name="14" value ="0" >疲劳驾驶预警</input>
        </td>
    </tr>
    <tr>
        <td>
            <input type="checkbox" name="18" value ="0" >当天累计驾驶超时</input>
        </td>
        <td>
            <input type="checkbox" name="19" value ="0" >超时停车</input>
        </td>
        <td>
            <input type="checkbox" name="20" value ="0" >进出区域</input>
        </td>
        <td>
            <input type="checkbox" name="21" value ="0" >进出路线</input>
        </td>
        <td>
            <input type="checkbox" name="22" value ="0" >路段行驶时间不足/过长</input>
        </td>
    </tr>
    <tr>
        <td>
            <input type="checkbox" name="23" value ="0" >路线偏离报警</input>
        </td>
        <td>
            <input type="checkbox" name="24" value ="0" >车辆VSS 故障</input>
        </td>
        <td>
            <input type="checkbox" name="25" value ="0" >车辆油量异常</input>
        </td>
        <td>
            <input type="checkbox" name="26" value ="0" >车辆被盗</input>
        </td>
        <td>
            <input type="checkbox" name="27" value ="0" >车辆非法点火</input>
        </td>
    </tr>
    <tr>
        <td>
            <input type="checkbox" name="28" value ="0" >车辆非法位移</input>
        </td>
        <td>
            <input type="checkbox" name="29" value ="0" >碰撞预警</input>
        </td>
        <td>
            <input type="checkbox" name="30" value ="0" >侧翻预警</input>
        </td>
        <td>
            <input type="checkbox" name="31" value ="0" >非法开门报警</input>
        </td>
    </tr>
</table>