<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
        <title>Login</title>
        <script src="/js/modernizr.custom.63321.js"></script>
        <link rel="stylesheet" type="text/css" href="/css/login.css" />
                <!--[if lte IE 7]><style>.main{display:none;} .support-note .note-ie{display:block;}</style><![endif]-->
    </head>
    <body>
        <div class="container">
            <section class="main">
                <form class="form-1" method="post" action="/authen/login/login">
                    <input type="hidden" name="act" value="login">
                    <p class="field">
                        <input type="text" name="username" placeholder="用户名">
                        <i class="icon-user icon-large"></i>
                    </p>
                    <p class="field">
                        <input type="password" name="password" placeholder="密码">
                        <i class="icon-lock icon-large"></i>
                    </p>
                    <p class="submit">
                        <button type="submit" name="submit"><i class="icon-arrow-right icon-large"></i></button>
                    </p>
                </form>
            </section>
        </div>
        <div><?php $this->message ?></div>
    </body>
</html>